-- servicio = { codigo, nombre (v), descripcion (v),  }
create table SERVICEPORTFOLIO (
	CODE VARCHAR(10) NOT NULL,
	NAME VARCHAR(120) NOT NULL,
	DESCRIPTION VARCHAR(400) NOT NULL
);
ALTER TABLE SERVICEPORTFOLIO ADD CONSTRAINT PK1_SERVICEPORTFOLIO PRIMARY KEY(CODE);