-- servicio = { codigo, nombre (v), descripcion (v),  }
create table SERVICIO (
	CODIGO VARCHAR(10) NOT NULL,
	NOMBRE VARCHAR(120) NOT NULL,
	DESCRIPCION VARCHAR(400) NOT NULL
);
ALTER TABLE SERVICIO ADD CONSTRAINT PK1_SERVICIO PRIMARY KEY(CODIGO);