CREATE TABLE BPMMDR.BPM_USERTASK 
(
  USERTASK_ID VARCHAR2(32 BYTE) NOT NULL 
, IMPLEMENTATION VARCHAR2(200 BYTE) 
, CONSTRAINT SYS_C0012580 PRIMARY KEY 
  (
    USERTASK_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE BPMMDR.BPM_SWIMLANE 
(
  PROCESS_ID VARCHAR2(32 BYTE) NOT NULL 
, SWIMLANE_ID VARCHAR2(32 BYTE) NOT NULL 
, NAME VARCHAR2(120 BYTE) NOT NULL 
, CONSTRAINT SYS_C0012534 PRIMARY KEY 
  (
    SWIMLANE_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE BPMMDR.BPM_SERVICETASK 
(
  SERVICETASK_ID VARCHAR2(32 BYTE) NOT NULL 
, IMPLEMENTATION VARCHAR2(200 BYTE) 
, CONSTRAINT SYS_C0012583 PRIMARY KEY 
  (
    SERVICETASK_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE BPMMDR.BPM_SEQUENCEFLOW 
(
  INCOMING_ID VARCHAR2(32 BYTE) NOT NULL 
, OUTGOING_ID VARCHAR2(32 BYTE) NOT NULL 
, CONSTRAINT SYS_C0012557 PRIMARY KEY 
  (
    INCOMING_ID 
  , OUTGOING_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE BPMMDR.BPM_SCRIPTTASK 
(
  SCRIPTTASK_ID VARCHAR2(32 BYTE) NOT NULL 
, SCRIPT VARCHAR2(4000 BYTE) NOT NULL 
, SCRIPTFORMAT VARCHAR2(20 BYTE) 
, CONSTRAINT SYS_C0012577 PRIMARY KEY 
  (
    SCRIPTTASK_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE BPMMDR.BPM_PROCESS 
(
  PROCESS_ID VARCHAR2(32 BYTE) NOT NULL 
, NAME VARCHAR2(120 BYTE) NOT NULL 
, CREATIONDATE DATE NOT NULL 
, CONSTRAINT SYS_C0012529 PRIMARY KEY 
  (
    PROCESS_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE BPMMDR.BPM_POOL 
(
  PROCESS_ID VARCHAR2(32 BYTE) NOT NULL 
, POOL_ID VARCHAR2(32 BYTE) NOT NULL 
, CONSTRAINT SYS_C0012543 PRIMARY KEY 
  (
    POOL_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE BPMMDR.BPM_PARTICIPANT 
(
  PARTICIPANT_ID VARCHAR2(32 BYTE) NOT NULL 
, USERORGROUP CHAR(1 BYTE) NOT NULL 
, NAME VARCHAR2(32 BYTE) NOT NULL 
, LANE_ID VARCHAR2(32 BYTE) NOT NULL 
, CONSTRAINT SYS_C0012549 PRIMARY KEY 
  (
    PARTICIPANT_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE BPMMDR.BPM_MODELVERSION 
(
  MINOR NUMBER(*, 0) NOT NULL 
, MAJOR NUMBER(*, 0) NOT NULL 
, RELEASEDATE DATE NOT NULL 
, CONSTRAINT SYS_C0012523 PRIMARY KEY 
  (
    MINOR 
  , MAJOR 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE BPMMDR.BPM_LANE 
(
  PROCESS_ID VARCHAR2(32 BYTE) NOT NULL 
, LANE_ID VARCHAR2(32 BYTE) NOT NULL 
, CONSTRAINT SYS_C0012539 PRIMARY KEY 
  (
    LANE_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE BPMMDR.BPM_GATEWAYDIR 
(
  DIRECTION_ID NUMBER(*, 0) NOT NULL 
, NAME VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT SYS_C0012562 PRIMARY KEY 
  (
    DIRECTION_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE BPMMDR.BPM_GATEWAY 
(
  GATEWAY_ID VARCHAR2(32 BYTE) NOT NULL 
, DIRECTION_ID NUMBER(*, 0) NOT NULL 
, CONSTRAINT SYS_C0012565 PRIMARY KEY 
  (
    GATEWAY_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE BPMMDR.BPM_FLOWNODE 
(
  FLOWNODE_ID VARCHAR2(32 BYTE) NOT NULL 
, NAME VARCHAR2(80 BYTE) 
, PROCESS_ID VARCHAR2(32 BYTE) NOT NULL 
, CONSTRAINT SYS_C0012553 PRIMARY KEY 
  (
    FLOWNODE_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE BPMMDR.BPM_EVENT 
(
  EVENT_ID VARCHAR2(32 BYTE) NOT NULL 
, EVENTTYPE_ID NUMBER(*, 0) NOT NULL 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE BPMMDR.BPM_BASEELEMENT 
(
  BASEELEMENT_ID VARCHAR2(32 BYTE) NOT NULL 
, DOCUMENTATION VARCHAR2(4000 BYTE) 
, CONSTRAINT SYS_C0012525 PRIMARY KEY 
  (
    BASEELEMENT_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE BPMMDR.BPM_ACTIVITY 
(
  ACTIVITY_ID VARCHAR2(32 BYTE) NOT NULL 
, ISFORCOMPENSATION NUMBER(*, 0) NOT NULL 
, CONSTRAINT SYS_C0012573 PRIMARY KEY 
  (
    ACTIVITY_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "SYSTEM" 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE BPMMDR.BPM_USERTASK
ADD CONSTRAINT SYS_C0012581 FOREIGN KEY
(
  USERTASK_ID 
)
REFERENCES BPMMDR.BPM_ACTIVITY
(
  ACTIVITY_ID 
)
ENABLE;

ALTER TABLE BPMMDR.BPM_SWIMLANE
ADD CONSTRAINT SYS_C0012535 FOREIGN KEY
(
  PROCESS_ID 
)
REFERENCES BPMMDR.BPM_PROCESS
(
  PROCESS_ID 
)
ENABLE;

ALTER TABLE BPMMDR.BPM_SWIMLANE
ADD CONSTRAINT SYS_C0012536 FOREIGN KEY
(
  SWIMLANE_ID 
)
REFERENCES BPMMDR.BPM_BASEELEMENT
(
  BASEELEMENT_ID 
)
ENABLE;

ALTER TABLE BPMMDR.BPM_SERVICETASK
ADD CONSTRAINT SYS_C0012584 FOREIGN KEY
(
  SERVICETASK_ID 
)
REFERENCES BPMMDR.BPM_ACTIVITY
(
  ACTIVITY_ID 
)
ENABLE;

ALTER TABLE BPMMDR.BPM_SEQUENCEFLOW
ADD CONSTRAINT SYS_C0012558 FOREIGN KEY
(
  INCOMING_ID 
)
REFERENCES BPMMDR.BPM_FLOWNODE
(
  FLOWNODE_ID 
)
ENABLE;

ALTER TABLE BPMMDR.BPM_SEQUENCEFLOW
ADD CONSTRAINT SYS_C0012559 FOREIGN KEY
(
  OUTGOING_ID 
)
REFERENCES BPMMDR.BPM_FLOWNODE
(
  FLOWNODE_ID 
)
ENABLE;

ALTER TABLE BPMMDR.BPM_SCRIPTTASK
ADD CONSTRAINT SYS_C0012578 FOREIGN KEY
(
  SCRIPTTASK_ID 
)
REFERENCES BPMMDR.BPM_ACTIVITY
(
  ACTIVITY_ID 
)
ENABLE;

ALTER TABLE BPMMDR.BPM_PROCESS
ADD CONSTRAINT SYS_C0012530 FOREIGN KEY
(
  PROCESS_ID 
)
REFERENCES BPMMDR.BPM_BASEELEMENT
(
  BASEELEMENT_ID 
)
ENABLE;

ALTER TABLE BPMMDR.BPM_POOL
ADD CONSTRAINT SYS_C0012544 FOREIGN KEY
(
  POOL_ID 
)
REFERENCES BPMMDR.BPM_SWIMLANE
(
  SWIMLANE_ID 
)
ENABLE;

ALTER TABLE BPMMDR.BPM_PARTICIPANT
ADD CONSTRAINT SYS_C0012550 FOREIGN KEY
(
  LANE_ID 
)
REFERENCES BPMMDR.BPM_LANE
(
  LANE_ID 
)
ENABLE;

ALTER TABLE BPMMDR.BPM_LANE
ADD CONSTRAINT SYS_C0012540 FOREIGN KEY
(
  LANE_ID 
)
REFERENCES BPMMDR.BPM_SWIMLANE
(
  SWIMLANE_ID 
)
ENABLE;

ALTER TABLE BPMMDR.BPM_GATEWAY
ADD CONSTRAINT SYS_C0012566 FOREIGN KEY
(
  GATEWAY_ID 
)
REFERENCES BPMMDR.BPM_FLOWNODE
(
  FLOWNODE_ID 
)
ENABLE;

ALTER TABLE BPMMDR.BPM_GATEWAY
ADD CONSTRAINT SYS_C0012567 FOREIGN KEY
(
  DIRECTION_ID 
)
REFERENCES BPMMDR.BPM_GATEWAYDIR
(
  DIRECTION_ID 
)
ENABLE;

ALTER TABLE BPMMDR.BPM_FLOWNODE
ADD CONSTRAINT SYS_C0012554 FOREIGN KEY
(
  PROCESS_ID 
)
REFERENCES BPMMDR.BPM_PROCESS
(
  PROCESS_ID 
)
ENABLE;

ALTER TABLE BPMMDR.BPM_EVENT
ADD CONSTRAINT SYS_C0012570 FOREIGN KEY
(
  EVENT_ID 
)
REFERENCES BPMMDR.BPM_FLOWNODE
(
  FLOWNODE_ID 
)
ENABLE;

ALTER TABLE BPMMDR.BPM_ACTIVITY
ADD CONSTRAINT SYS_C0012574 FOREIGN KEY
(
  ACTIVITY_ID 
)
REFERENCES BPMMDR.BPM_FLOWNODE
(
  FLOWNODE_ID 
)
ENABLE;
