create table SERVICE (
	CODE VARCHAR(10) NOT NULL
);
ALTER TABLE SERVICE ADD CONSTRAINT PK1_SERVICE PRIMARY KEY(CODE);
create table SERVICEVERSION (
	CODE VARCHAR(10) NOT NULL,
	VERSION VARCHAR(6) NOT NULL,
	NAME VARCHAR(120) NOT NULL,
	DESCRIPTION VARCHAR(400) NOT NULL,
	PARENTVERSION VARCHAR(6) NULL,
	PORTFOLIO_CODE VARCHAR(10) NOT NULL
);
ALTER TABLE SERVICEVERSION ADD CONSTRAINT PK1_SERVICEVERSION PRIMARY KEY(CODE,VERSION);
ALTER TABLE SERVICEVERSION ADD CONSTRAINT FK1_SERVICEVERSION FOREIGN KEY (PORTFOLIO_CODE)
	REFERENCES SERVICEPORTFOLIO(CODE);