-- R1 (party) = { #id +nombre descripcion }
-- R3 (party relationship type) = { #id +name }
-- R4 (party relationship role type) = { #R3.id #name +description }
-- R5 (party relationship) = { #id +R3.id }
-- R6 (party relationship role) = { #R5.id #R4.id #since -thru }
--
-- METAMODELING
create table PARTYTYPE (
	ID INT NOT NULL,
	NAME VARCHAR(40) NOT NULL,
	PARENT_ID INT NULL
); 
ALTER TABLE PARTYTYPE ADD CONSTRAINT PK1_PARTYTYPE PRIMARY KEY(ID);
ALTER TABLE PARTYTYPE ADD CONSTRAINT FK1_PARTYTYPE FOREIGN KEY (PARENT_ID) 
	REFERENCES PARTYTYPE (ID);
	
create table PARTY (
	ID INT NOT NULL,
	NAME VARCHAR(120) NOT NULL,
	DESCRIPTION VARCHAR(4000) NULL,
	PARTYTYPE_ID INT NOT NULL
);
ALTER TABLE PARTY ADD CONSTRAINT PK1_PARTY PRIMARY KEY(ID);
ALTER TABLE PARTY ADD CONSTRAINT FK1_PARTY FOREIGN KEY (PARTYTYPE_ID) 
	REFERENCES PARTYTYPE (ID);
	
create table PARTYRELATIONSHIPTYPE (
	ID INT NOT NULL,
	NAME VARCHAR(120) NOT NULL,
	DESCRIPTION VARCHAR(4000) NULL
);
ALTER TABLE PARTYRELATIONSHIPTYPE  ADD CONSTRAINT PK1_PARTYRELATIONSHIPTYPE PRIMARY KEY(ID);

create table PARTYRELROLETYPE (
	PARTYRELTYPE_ID INT NOT NULL,
	ID VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(4000) NULL,
	PARTYTYPE_ID INT NOT NULL
);
ALTER TABLE PARTYRELROLETYPE ADD CONSTRAINT PK1_PARTYRELROLETYPE PRIMARY KEY(PARTYRELTYPE_ID,ID);
ALTER TABLE PARTYRELROLETYPE ADD CONSTRAINT FK1_PARTYRELROLETYPE FOREIGN KEY (PARTYRELTYPE_ID) 
	REFERENCES PARTYRELATIONSHIPTYPE (ID);
ALTER TABLE PARTYRELROLETYPE ADD CONSTRAINT FK2_PARTYRELROLETYPE FOREIGN KEY (PARTYTYPE_ID) 
	REFERENCES PARTYTYPE (ID);

create table PARTYRELATIONSHIP (
	ID INT NOT NULL,
	PARTYRELTYPE_ID INT NOT NULL,
	FROMDATE DATE NOT NULL,
	THRUDATE DATE NULL
);
ALTER TABLE PARTYRELATIONSHIP ADD CONSTRAINT PK1_PARTYRELATIONSHIP PRIMARY KEY(ID);
ALTER TABLE PARTYRELATIONSHIP ADD CONSTRAINT UK1_PARTYRELATIONSHIP UNIQUE KEY(PARTYRELTYPE_ID,FROMDATE);
ALTER TABLE PARTYRELATIONSHIP ADD CONSTRAINT FK1_PARTYRELATIONSHIP FOREIGN KEY (PARTYRELTYPE_ID) 
	REFERENCES PARTYRELATIONSHIPTYPE (ID);

create table PARTYRELROLE (
	PARTYRELATIONSHIP_ID NOT NULL, /* Relacion */
	PARTYRELTYPE_ID INT NOT NULL, /* Role */
	PARTY_ID INT NOT NULL, /* Entidad */
	FROMDATE DATE NOT NULL, /* Desde */
	ID VARCHAR(20) NOT NULL,	
	THRUDATE DATE NULL
);
ALTER TABLE PARTYRELATIONSHIP ADD CONSTRAINT PK1_PARTYRELATIONSHIP PRIMARY KEY(ID);

create table BUSINESSOBJECT (
	PARTY_ID INT NOT NULL
);
create table BASEDATAELEMENT (
	PARTY_ID INT NOT NULL
);
create table BUSINESSOBJECT (
	PARTY_ID INT NOT NULL
);

-- Requirements Management Specification
create table REQUIREMENT (
	PARTY_ID INT NOT NULL
);

create table REQCATALOG (
	PARTY_ID INT NOT NULL,
	CREATIONDATE DATE NOT NULL
);