create table APLICACION (
	CODE VARCHAR(10) NOT NULL,
	NAME VARCHAR(120) NOT NULL
);
ALTER TABLE APLICACION ADD CONSTRAINT PK1_APLICACION PRIMARY KEY(CODE);
create table APLICACION_SERVICIO (
	APLICACION_CODE VARCHAR(10) NOT NULL,
	SERVICIO_CODE VARCHAR(10) NOT NULL,
	SERVICIO_VERSION VARCHAR(6) NOT NULL
);
ALTER TABLE APLICACION_SERVICIO ADD CONSTRAINT PK1_APLICACION_SERVICIO PRIMARY KEY(APLICACION_CODE, SERVICIO_CODE,SERVICIO_VERSION);
ALTER TABLE APLICACION_SERVICIO ADD CONSTRAINT FK1_APLICACION_SERVICIO FOREIGN KEY (SERVICIO_CODE,SERVICIO_VERSION) 
	REFERENCES SERVICEVERSION (CODE,VERSION);
ALTER TABLE APLICACION_SERVICIO ADD CONSTRAINT FK2_APLICACION_SERVICIO FOREIGN KEY (APLICACION_CODE) 
	REFERENCES APLICACION (CODE);