-- METAMODELING
-- @Author: Ilver Anache Pupo
-- @Company: CROSSNET SAC
--
-- DATE			Author 			DESCRIPTION
-- ----------------------------------------------------------------------------
-- 17/10/2015	Ilver Anache	Creacion  inicial
create table PARTYTYPE (
	ID INT NOT NULL,
	NAME VARCHAR(40) NOT NULL
); 
ALTER TABLE PARTYTYPE ADD CONSTRAINT PK1_PARTYTYPE PRIMARY KEY(ID);

create table PARTYTYPEINHERITANCE (
	PARTYTYPE_PARENT_ID INT NOT NULL,
	PARTYTYPE_CHILD_ID INT NOT NULL
);
ALTER TABLE PARTYTYPEINHERITANCE ADD CONSTRAINT PK1_PARTYTYPEINHERITANCE PRIMARY KEY (PARTYTYPE_PARENT_ID,PARTYTYPE_CHILD_ID);
ALTER TABLE PARTYTYPEINHERITANCE ADD CONSTRAINT FK1_PARTYTYPEINHERITANCE FOREIGN KEY (PARTYTYPE_PARENT_ID) 
	REFERENCES PARTYTYPE (ID);
ALTER TABLE PARTYTYPEINHERITANCE ADD CONSTRAINT FK2_PARTYTYPEINHERITANCE FOREIGN KEY (PARTYTYPE_CHILD_ID) 
	REFERENCES PARTYTYPE (ID);
	
create table PARTYRELATIONSHIPTYPE (
	ID INT NOT NULL,
	NAME VARCHAR(120) NOT NULL,
	DESCRIPTION VARCHAR(4000) NULL
);
ALTER TABLE PARTYRELATIONSHIPTYPE  ADD CONSTRAINT PK1_PARTYRELATIONSHIPTYPE PRIMARY KEY(ID);

create table PARTYRELROLETYPE (
	PARTYRELTYPE_ID INT NOT NULL,
	ID VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(4000) NULL,
	PARTYTYPE_ID INT NOT NULL,
	MINOCCUR CHAR NOT NULL,
	MAXOCCUR CHAR NOT NULL
);
ALTER TABLE PARTYRELROLETYPE ADD CONSTRAINT PK1_PARTYRELROLETYPE PRIMARY KEY(PARTYRELTYPE_ID,ID);
ALTER TABLE PARTYRELROLETYPE ADD CONSTRAINT FK1_PARTYRELROLETYPE FOREIGN KEY (PARTYRELTYPE_ID) 
	REFERENCES PARTYRELATIONSHIPTYPE (ID);
ALTER TABLE PARTYRELROLETYPE ADD CONSTRAINT FK2_PARTYRELROLETYPE FOREIGN KEY (PARTYTYPE_ID) 
	REFERENCES PARTYTYPE (ID);