-- MODEL RELATIONSHIPS
-- @Author: Ilver Anache Pupo
-- @Company: CROSSNET SAC
--
-- DATE			Author 			DESCRIPTION
-- ----------------------------------------------------------------------------
-- 17/10/2015	Ilver Anache	Creacion  inicial

create table PARTYRELATIONSHIP (
	ID INT NOT NULL,
	PARTYRELTYPE_ID INT NOT NULL,
	FROMDATE DATE NOT NULL,
	THRUDATE DATE NULL
);
ALTER TABLE PARTYRELATIONSHIP ADD CONSTRAINT PK1_PARTYRELATIONSHIP PRIMARY KEY(ID);
ALTER TABLE PARTYRELATIONSHIP ADD CONSTRAINT UK1_PARTYRELATIONSHIP UNIQUE (PARTYRELTYPE_ID,FROMDATE);
ALTER TABLE PARTYRELATIONSHIP ADD CONSTRAINT FK1_PARTYRELATIONSHIP FOREIGN KEY (PARTYRELTYPE_ID) 
	REFERENCES PARTYRELATIONSHIPTYPE (ID);

create table PARTYRELROLE (
	PARTYRELATIONSHIP_ID INT NOT NULL, /* Relacion */
	PARTYRELTYPE_ID INT NOT NULL, /* Role */
	PARTY_ID INT NOT NULL, /* Entidad */
	FROMDATE DATE NOT NULL, /* Desde */
	ID VARCHAR(20) NOT NULL,	
	THRUDATE DATE NULL
);
ALTER TABLE PARTYRELROLE ADD CONSTRAINT PK1_PARTYRELROLE PRIMARY KEY(ID);